/* THIS FILE IS AUTOGENERATED BY CBINDGEN. DO NOT MODIFY IT. */

#ifndef DESKMSG_C_H
#define DESKMSG_C_H

#pragma once

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

deskmsg_ErrorCode tiny_protocol_get_config(char *output_ptr);

deskmsg_ErrorCode tiny_protocol_discovery(const char *service_ptr,
                                          uint64_t seconds,
                                          char *output_str_ptr,
                                          uintptr_t output_str_len);

deskmsg_ErrorCode tiny_protocol_start_server(const char *config_ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DESKMSG_C_H */
