/* THIS FILE IS AUTOGENERATED BY CBINDGEN. DO NOT MODIFY IT. */

#ifndef DESKMSG_C_H
#define DESKMSG_C_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum deskmsg_ErrorCode {
  Ok = 0,
  BadConfig = 1,
  StartServerError = 2,
  InvalidServerPoint = 3,
  ServerHasInit = 4,
  MDNSInitFailure = 5,
  OutOfAllocatedBounds = 6,
} deskmsg_ErrorCode;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

enum deskmsg_ErrorCode deskmsg_get_config(char *output_ptr);

enum deskmsg_ErrorCode deskmsg_discovery(const char *service_ptr,
                                         uint64_t seconds,
                                         char *output_str_ptr,
                                         uintptr_t output_str_len);

enum deskmsg_ErrorCode deskmsg_start_server(const char *config_ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DESKMSG_C_H */
