extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_cpp_compat(true)
        // .with_no_includes()
        .with_pragma_once(true)
        .with_include_guard("DESKMSG_C_H")
        .with_item_prefix("deskmsg_") // Optional: to prefix all generated items
        .with_header("/* THIS FILE IS AUTOGENERATED BY CBINDGEN. DO NOT MODIFY IT. */")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("include/deskmsg_c.h");
}
