/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function discoveryMdns(serviceName: string, seconds: number): Array<NapiServiceInfo>

export declare function getConfig(): NapiServerConfig

export interface NapiProperty {
  key: string
  value: string
}

export interface NapiServerConfig {
  mqttAddress: string
  httpAddress: string
  basicPath: string
  httpAuthToken: string
}

export interface NapiServiceInfo {
  fullname: string
  hostname: string
  port: number
  addresses: Array<string>
  properties: Array<NapiProperty>
}

export declare function startServer(config: NapiServerConfig): void
