/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NapiServerConfig {
  mqttAddress: string
  httpAddress: string
  basicPath: string
  httpAuthToken: string
}
export interface NapiProperty {
  key: string
  value: string
}
export interface NapiServiceInfo {
  fullname: string
  hostname: string
  port: number
  addresses: Array<string>
  properties: Array<NapiProperty>
}
export declare function startServerNapi(config: NapiServerConfig): void
export declare function getConfigNapi(): NapiServerConfig
export declare function discoveryNapi(serviceName: string, seconds: number): Array<NapiServiceInfo>
