name: ci
on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: make prepare-linux
          - host: macos-latest
            target: aarch64-apple-darwin
            build: make prepare-mac-aarch64
          - host: macos-latest
            target: x86_64-apple-darwin
            build: make prepare-mac-x86_64
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: make prepare-windows

    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: install libs
        run: ${{ matrix.settings.build }}

      - name: code format check
        run: cargo fmt --check
      - name: Build
        run: cargo build --release --target=${{ matrix.settings.target }}
#
#      - name: run example
#        run: |
#          cd examples/c_example
#          cmake  -DCMAKE_BUILD_TYPE=Release

