name: ci.yml
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: make release-linux
          - host: macos-12
            target: x86_64-apple-darwin
            build: make release-mac-x86_64
          - host: macos-13-xlarge
            target: aarch64-apple-darwin
            build: make release-mac-aarch64
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: make release-windows

    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: code format check
        run: cargo fmt --check
      - name: Build
        run: cargo build --release
#
#      - name: run example
#        run: |
#          cd examples/c_example
#          cmake  -DCMAKE_BUILD_TYPE=Release

