name: napi ci
env:
  DEBUG: napi:*
  APP_NAME: deskmsg_napi
permissions:
  contents: write
  id-token: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/workflows/cd.yml'
      - '.github/workflows/ci.yml'
      - 'README.md'
      - '.gitignore'
      - 'bin'
      - 'deskmsg_c'
      - 'examples'
      - 'Makefile'
  pull_request: null

jobs:
  build:
    uses: ./.github/workflows/napi_build.yml
  test-macOS-windows-binding:
    name: Test bindings on ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-13
            target: x86_64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
        node:
          - '18'
          # - '20' windows would: Process completed with exit code 1.  test in my computer, and everything is ok
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          architecture: x64
          cache-dependency-path: deskmsg_napi
      - name: Install dependencies
        run: npm ci
        working-directory: deskmsg_napi
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: deskmsg_napi/
      - name: List packages
        run: ls -R .
        shell: bash
        working-directory: deskmsg_napi
      - name: Test bindings
        run: npm test
        working-directory: deskmsg_napi
  test-linux-x64-gnu-binding:
    name: Test bindings on Linux-x64-gnu - node@${{ matrix.node }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node:
          - '18'
          - '20'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: deskmsg_napi
      - name: Install dependencies
        run: npm ci
        working-directory: deskmsg_napi
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-x86_64-unknown-linux-gnu
          path: deskmsg_napi/
      - name: Test bindings
        run: docker run --rm -v $(pwd):/build -w /build/deskmsg_napi node:${{ matrix.node }}-slim npm test

